# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\contract_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ContractFormInsert(object):
    def setupUi(self, ContractFormInsert):
        ContractFormInsert.setObjectName("ContractFormInsert")
        ContractFormInsert.resize(286, 314)
        self.formLayout = QtWidgets.QFormLayout(ContractFormInsert)
        self.formLayout.setObjectName("formLayout")
        self.relationLabel = QtWidgets.QLabel(ContractFormInsert)
        self.relationLabel.setObjectName("relationLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.relationLabel)
        self.relationComboBox = MyComboBox(ContractFormInsert)
        self.relationComboBox.setObjectName("relationComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.relationComboBox)
        self.userLabel = QtWidgets.QLabel(ContractFormInsert)
        self.userLabel.setObjectName("userLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.userLabel)
        self.userComboBox = MyComboBox(ContractFormInsert)
        self.userComboBox.setObjectName("userComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userComboBox)
        self.accountLabel = QtWidgets.QLabel(ContractFormInsert)
        self.accountLabel.setObjectName("accountLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.accountLabel)
        self.accountComboBox = MyComboBox(ContractFormInsert)
        self.accountComboBox.setObjectName("accountComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accountComboBox)
        self.letterLabel = QtWidgets.QLabel(ContractFormInsert)
        self.letterLabel.setObjectName("letterLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.letterLabel)
        self.letterComboBox = MyComboBox(ContractFormInsert)
        self.letterComboBox.setObjectName("letterComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.letterComboBox)
        self.referenceLabel = QtWidgets.QLabel(ContractFormInsert)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(ContractFormInsert)
        self.referenceLineEdit.setToolTip("")
        self.referenceLineEdit.setStatusTip("")
        self.referenceLineEdit.setAccessibleDescription("")
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.emailLabel = QtWidgets.QLabel(ContractFormInsert)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.emailComboBox = MyComboBox(ContractFormInsert)
        self.emailComboBox.setObjectName("emailComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.emailComboBox)
        self.amountLabel = QtWidgets.QLabel(ContractFormInsert)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.amountLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(ContractFormInsert)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.startDateLabel = QtWidgets.QLabel(ContractFormInsert)
        self.startDateLabel.setObjectName("startDateLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.startDateLabel)
        self.startDateDateEdit = QtWidgets.QDateEdit(ContractFormInsert)
        self.startDateDateEdit.setEnabled(True)
        self.startDateDateEdit.setWrapping(False)
        self.startDateDateEdit.setFrame(True)
        self.startDateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.startDateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.startDateDateEdit.setCalendarPopup(True)
        self.startDateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.startDateDateEdit.setObjectName("startDateDateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.startDateDateEdit)
        self.endDateLabel = QtWidgets.QLabel(ContractFormInsert)
        self.endDateLabel.setObjectName("endDateLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.endDateLabel)
        self.endDateDateEdit = QtWidgets.QDateEdit(ContractFormInsert)
        self.endDateDateEdit.setEnabled(True)
        self.endDateDateEdit.setWrapping(False)
        self.endDateDateEdit.setFrame(True)
        self.endDateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.endDateDateEdit.setCalendarPopup(True)
        self.endDateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.endDateDateEdit.setObjectName("endDateDateEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.endDateDateEdit)
        self.recurenceLabel = QtWidgets.QLabel(ContractFormInsert)
        self.recurenceLabel.setObjectName("recurenceLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.recurenceLabel)
        self.recurenceBox = QtWidgets.QSpinBox(ContractFormInsert)
        self.recurenceBox.setObjectName("recurenceBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.recurenceBox)

        self.retranslateUi(ContractFormInsert)
        QtCore.QMetaObject.connectSlotsByName(ContractFormInsert)

    def retranslateUi(self, ContractFormInsert):
        _translate = QtCore.QCoreApplication.translate
        ContractFormInsert.setWindowTitle(_translate("ContractFormInsert", "Form"))
        self.relationLabel.setText(_translate("ContractFormInsert", "Relation"))
        self.userLabel.setText(_translate("ContractFormInsert", "User"))
        self.accountLabel.setText(_translate("ContractFormInsert", "Bank account"))
        self.letterLabel.setText(_translate("ContractFormInsert", "Letter"))
        self.referenceLabel.setText(_translate("ContractFormInsert", "Reference"))
        self.emailLabel.setText(_translate("ContractFormInsert", "Email"))
        self.amountLabel.setText(_translate("ContractFormInsert", "Amount"))
        self.startDateLabel.setText(_translate("ContractFormInsert", "Date"))
        self.endDateLabel.setText(_translate("ContractFormInsert", "End Date"))
        self.recurenceLabel.setText(_translate("ContractFormInsert", "Recurence"))

from MyQtness.myWidgets import MyComboBox
