# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\contract_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LetterFormInsert(object):
    def setupUi(self, LetterFormInsert):
        LetterFormInsert.setObjectName("LetterFormInsert")
        LetterFormInsert.resize(286, 314)
        self.formLayout = QtWidgets.QFormLayout(LetterFormInsert)
        self.formLayout.setObjectName("formLayout")
        self.senderLabel = QtWidgets.QLabel(LetterFormInsert)
        self.senderLabel.setObjectName("senderLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.senderLabel)
        self.senderComboBox = MyComboBox(LetterFormInsert)
        self.senderComboBox.setObjectName("senderComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.senderComboBox)
        self.UserLabel = QtWidgets.QLabel(LetterFormInsert)
        self.UserLabel.setObjectName("UserLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.UserLabel)
        self.userComboBox = MyComboBox(LetterFormInsert)
        self.userComboBox.setObjectName("userComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.userComboBox)
        self.bankAccountLabel = QtWidgets.QLabel(LetterFormInsert)
        self.bankAccountLabel.setObjectName("bankAccountLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.bankAccountLabel)
        self.bankAccountComboBox = MyComboBox(LetterFormInsert)
        self.bankAccountComboBox.setObjectName("bankAccountComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.bankAccountComboBox)
        self.letterLabel = QtWidgets.QLabel(LetterFormInsert)
        self.letterLabel.setObjectName("letterLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.letterLabel)
        self.letterComboBox = MyComboBox(LetterFormInsert)
        self.letterComboBox.setObjectName("letterComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.letterComboBox)
        self.referenceLabel = QtWidgets.QLabel(LetterFormInsert)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(LetterFormInsert)
        self.referenceLineEdit.setToolTip("")
        self.referenceLineEdit.setStatusTip("")
        self.referenceLineEdit.setAccessibleDescription("")
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.emailLabel = QtWidgets.QLabel(LetterFormInsert)
        self.emailLabel.setObjectName("emailLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.emailLabel)
        self.emailComboBox = MyComboBox(LetterFormInsert)
        self.emailComboBox.setObjectName("emailComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.emailComboBox)
        self.amountLabel = QtWidgets.QLabel(LetterFormInsert)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.amountLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(LetterFormInsert)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.startDateLabel = QtWidgets.QLabel(LetterFormInsert)
        self.startDateLabel.setObjectName("startDateLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.startDateLabel)
        self.startDateDateEdit = QtWidgets.QDateEdit(LetterFormInsert)
        self.startDateDateEdit.setEnabled(True)
        self.startDateDateEdit.setWrapping(False)
        self.startDateDateEdit.setFrame(True)
        self.startDateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.startDateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.startDateDateEdit.setCalendarPopup(True)
        self.startDateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.startDateDateEdit.setObjectName("startDateDateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.startDateDateEdit)
        self.endDateLabel = QtWidgets.QLabel(LetterFormInsert)
        self.endDateLabel.setObjectName("endDateLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.endDateLabel)
        self.endDateDateEdit = QtWidgets.QDateEdit(LetterFormInsert)
        self.endDateDateEdit.setEnabled(True)
        self.endDateDateEdit.setWrapping(False)
        self.endDateDateEdit.setFrame(True)
        self.endDateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.endDateDateEdit.setCalendarPopup(True)
        self.endDateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.endDateDateEdit.setObjectName("endDateDateEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.endDateDateEdit)
        self.occurenceLabel = QtWidgets.QLabel(LetterFormInsert)
        self.occurenceLabel.setObjectName("occurenceLabel")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.occurenceLabel)
        self.occurenceBox = QtWidgets.QSpinBox(LetterFormInsert)
        self.occurenceBox.setObjectName("occurenceBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.occurenceBox)

        self.retranslateUi(LetterFormInsert)
        QtCore.QMetaObject.connectSlotsByName(LetterFormInsert)

    def retranslateUi(self, LetterFormInsert):
        _translate = QtCore.QCoreApplication.translate
        LetterFormInsert.setWindowTitle(_translate("LetterFormInsert", "Form"))
        self.senderLabel.setText(_translate("LetterFormInsert", "Relation"))
        self.UserLabel.setText(_translate("LetterFormInsert", "User"))
        self.bankAccountLabel.setText(_translate("LetterFormInsert", "Bank account"))
        self.letterLabel.setText(_translate("LetterFormInsert", "Letter"))
        self.referenceLabel.setText(_translate("LetterFormInsert", "Reference"))
        self.emailLabel.setText(_translate("LetterFormInsert", "Email"))
        self.amountLabel.setText(_translate("LetterFormInsert", "Amount"))
        self.startDateLabel.setText(_translate("LetterFormInsert", "Date"))
        self.endDateLabel.setText(_translate("LetterFormInsert", "End Date"))
        self.occurenceLabel.setText(_translate("LetterFormInsert", "Occurence"))

from MyQtness.myWidgets import MyComboBox
