# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\letter_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_letter_form(object):
    def setupUi(self, letter_form):
        letter_form.setObjectName("letter_form")
        letter_form.resize(300, 300)
        letter_form.setStyleSheet("")
        self.centralWidget = QtWidgets.QWidget(letter_form)
        self.centralWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralWidget.setObjectName("centralWidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralWidget)
        self.formLayout.setContentsMargins(11, 11, 11, 11)
        self.formLayout.setHorizontalSpacing(20)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setObjectName("formLayout")
        self.dateLabel = QtWidgets.QLabel(self.centralWidget)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.dateDateEdit = QtWidgets.QDateEdit(self.centralWidget)
        self.dateDateEdit.setWrapping(False)
        self.dateDateEdit.setFrame(True)
        self.dateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.dateDateEdit.setCalendarPopup(True)
        self.dateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.dateDateEdit.setObjectName("dateDateEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dateDateEdit)
        self.senderLabel = QtWidgets.QLabel(self.centralWidget)
        self.senderLabel.setObjectName("senderLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.senderLabel)
        self.senderLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.senderLineEdit.setObjectName("senderLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.senderLineEdit)
        self.subjectLabel = QtWidgets.QLabel(self.centralWidget)
        self.subjectLabel.setObjectName("subjectLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.subjectLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.UserLabel = QtWidgets.QLabel(self.centralWidget)
        self.UserLabel.setObjectName("UserLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.UserLabel)
        self.UserLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.UserLineEdit.setObjectName("UserLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.UserLineEdit)
        self.referenceLabel = QtWidgets.QLabel(self.centralWidget)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.referenceLineEdit.setToolTip("")
        self.referenceLineEdit.setStatusTip("")
        self.referenceLineEdit.setAccessibleDescription("")
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.scanLabel = QtWidgets.QLabel(self.centralWidget)
        self.scanLabel.setObjectName("scanLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.scanLabel)
        self.widget = QtWidgets.QWidget(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setAcceptDrops(True)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.widget)
        letter_form.setCentralWidget(self.centralWidget)

        self.retranslateUi(letter_form)
        QtCore.QMetaObject.connectSlotsByName(letter_form)

    def retranslateUi(self, letter_form):
        _translate = QtCore.QCoreApplication.translate
        letter_form.setWindowTitle(_translate("letter_form", "letter_form"))
        self.dateLabel.setText(_translate("letter_form", "Date"))
        self.senderLabel.setText(_translate("letter_form", "Sender"))
        self.subjectLabel.setText(_translate("letter_form", "Subject"))
        self.UserLabel.setText(_translate("letter_form", "Adressed User"))
        self.referenceLabel.setText(_translate("letter_form", "Reference"))
        self.scanLabel.setText(_translate("letter_form", "Scan"))
        self.label.setText(_translate("letter_form", "Drop file"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    letter_form = QtWidgets.QMainWindow()
    ui = Ui_letter_form()
    ui.setupUi(letter_form)
    letter_form.show()
    sys.exit(app.exec_())

