# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\letter_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LetterForm(object):
    def setupUi(self, LetterForm):
        LetterForm.setObjectName("LetterForm")
        LetterForm.resize(320, 559)
        LetterForm.setMaximumSize(QtCore.QSize(350, 16777215))
        LetterForm.setStyleSheet("#scanFileDrop {\n"
"    border: 1px solid #76797C;\n"
"    background-color: #232629;\n"
"    border-radius: 0px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(LetterForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(LetterForm)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonAdd = QtWidgets.QPushButton(LetterForm)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_2.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtWidgets.QPushButton(LetterForm)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_2.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtWidgets.QPushButton(LetterForm)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(LetterForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, 0, -1)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.dateLabel = QtWidgets.QLabel(LetterForm)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.dateDateEdit = QtWidgets.QDateEdit(LetterForm)
        self.dateDateEdit.setEnabled(True)
        self.dateDateEdit.setWrapping(False)
        self.dateDateEdit.setFrame(True)
        self.dateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.dateDateEdit.setCalendarPopup(True)
        self.dateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.dateDateEdit.setObjectName("dateDateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateDateEdit)
        self.subjectLabel = QtWidgets.QLabel(LetterForm)
        self.subjectLabel.setObjectName("subjectLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.subjectLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(LetterForm)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.UserLabel = QtWidgets.QLabel(LetterForm)
        self.UserLabel.setObjectName("UserLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.UserLabel)
        self.senderLabel = QtWidgets.QLabel(LetterForm)
        self.senderLabel.setObjectName("senderLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.senderLabel)
        self.referenceLabel = QtWidgets.QLabel(LetterForm)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(LetterForm)
        self.referenceLineEdit.setToolTip("")
        self.referenceLineEdit.setStatusTip("")
        self.referenceLineEdit.setAccessibleDescription("")
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.scanLabel = QtWidgets.QLabel(LetterForm)
        self.scanLabel.setObjectName("scanLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.scanLabel)
        self.scanFileDrop = MyDragDropBox(LetterForm)
        self.scanFileDrop.setMinimumSize(QtCore.QSize(0, 100))
        self.scanFileDrop.setAcceptDrops(True)
        self.scanFileDrop.setAutoFillBackground(False)
        self.scanFileDrop.setStyleSheet("")
        self.scanFileDrop.setObjectName("scanFileDrop")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scanFileDrop)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.scanFileDrop)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.scanFileDrop)
        self.userComboBox = MyComboBox(LetterForm)
        self.userComboBox.setObjectName("userComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userComboBox)
        self.senderComboBox = MyComboBox(LetterForm)
        self.senderComboBox.setObjectName("senderComboBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.senderComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSave = QtWidgets.QPushButton(LetterForm)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonReset = QtWidgets.QPushButton(LetterForm)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.horizontalLayout.addWidget(self.pushButtonReset)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LetterForm)
        QtCore.QMetaObject.connectSlotsByName(LetterForm)

    def retranslateUi(self, LetterForm):
        _translate = QtCore.QCoreApplication.translate
        LetterForm.setWindowTitle(_translate("LetterForm", "Form"))
        self.label.setText(_translate("LetterForm", "Letter list"))
        self.pushButtonAdd.setText(_translate("LetterForm", "Add new"))
        self.pushButtonEdit.setText(_translate("LetterForm", "Edit"))
        self.pushButtonDelete.setText(_translate("LetterForm", "Delete"))
        self.dateLabel.setText(_translate("LetterForm", "Date"))
        self.subjectLabel.setText(_translate("LetterForm", "Subject"))
        self.UserLabel.setText(_translate("LetterForm", "Adressed User"))
        self.senderLabel.setText(_translate("LetterForm", "Sender"))
        self.referenceLabel.setText(_translate("LetterForm", "Reference"))
        self.scanLabel.setText(_translate("LetterForm", "Scan"))
        self.label_3.setText(_translate("LetterForm", "Drop file"))
        self.pushButtonSave.setText(_translate("LetterForm", "Save"))
        self.pushButtonReset.setText(_translate("LetterForm", "Reset"))

from MyQtness.myWidgets import MyComboBox, MyDragDropBox
