# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\letter_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LetterForm(object):
    def setupUi(self, LetterForm):
        LetterForm.setObjectName("LetterForm")
        LetterForm.resize(290, 300)
        self.formLayout = QtWidgets.QFormLayout(LetterForm)
        self.formLayout.setObjectName("formLayout")
        self.dateLabel = QtWidgets.QLabel(LetterForm)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.dateDateEdit = QtWidgets.QDateEdit(LetterForm)
        self.dateDateEdit.setWrapping(False)
        self.dateDateEdit.setFrame(True)
        self.dateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.dateDateEdit.setCalendarPopup(True)
        self.dateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.dateDateEdit.setObjectName("dateDateEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.dateDateEdit)
        self.senderLabel = QtWidgets.QLabel(LetterForm)
        self.senderLabel.setObjectName("senderLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.senderLabel)
        self.senderLineEdit = QtWidgets.QLineEdit(LetterForm)
        self.senderLineEdit.setObjectName("senderLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.senderLineEdit)
        self.subjectLabel = QtWidgets.QLabel(LetterForm)
        self.subjectLabel.setObjectName("subjectLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.subjectLabel)
        self.subjectLineEdit = QtWidgets.QLineEdit(LetterForm)
        self.subjectLineEdit.setObjectName("subjectLineEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.subjectLineEdit)
        self.UserLabel = QtWidgets.QLabel(LetterForm)
        self.UserLabel.setObjectName("UserLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.UserLabel)
        self.UserLineEdit = QtWidgets.QLineEdit(LetterForm)
        self.UserLineEdit.setObjectName("UserLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.UserLineEdit)
        self.referenceLabel = QtWidgets.QLabel(LetterForm)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(LetterForm)
        self.referenceLineEdit.setToolTip("")
        self.referenceLineEdit.setStatusTip("")
        self.referenceLineEdit.setAccessibleDescription("")
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.scanLabel = QtWidgets.QLabel(LetterForm)
        self.scanLabel.setObjectName("scanLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.scanLabel)
        self.widget = QtWidgets.QWidget(LetterForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setAcceptDrops(True)
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 10, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.widget)

        self.retranslateUi(LetterForm)
        QtCore.QMetaObject.connectSlotsByName(LetterForm)

    def retranslateUi(self, LetterForm):
        _translate = QtCore.QCoreApplication.translate
        LetterForm.setWindowTitle(_translate("LetterForm", "Form"))
        self.dateLabel.setText(_translate("LetterForm", "Date"))
        self.senderLabel.setText(_translate("LetterForm", "Sender"))
        self.subjectLabel.setText(_translate("LetterForm", "Subject"))
        self.UserLabel.setText(_translate("LetterForm", "Adressed User"))
        self.referenceLabel.setText(_translate("LetterForm", "Reference"))
        self.scanLabel.setText(_translate("LetterForm", "Scan"))
        self.label.setText(_translate("LetterForm", "Drop file"))

