# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\relation_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RelationForm(object):
    def setupUi(self, RelationForm):
        RelationForm.setObjectName("RelationForm")
        RelationForm.resize(320, 559)
        RelationForm.setMaximumSize(QtCore.QSize(350, 16777215))
        RelationForm.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(RelationForm)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleLabel = QtWidgets.QLabel(RelationForm)
        self.titleLabel.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.titleLabel.setFont(font)
        self.titleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.titleLabel.setObjectName("titleLabel")
        self.verticalLayout.addWidget(self.titleLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonAdd = QtWidgets.QPushButton(RelationForm)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout_2.addWidget(self.pushButtonAdd)
        self.pushButtonEdit = QtWidgets.QPushButton(RelationForm)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_2.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtWidgets.QPushButton(RelationForm)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(RelationForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(-1, -1, 0, -1)
        self.formLayout.setSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.nameLabel = QtWidgets.QLabel(RelationForm)
        self.nameLabel.setObjectName("nameLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nameLabel)
        self.nameLineEdit = QtWidgets.QLineEdit(RelationForm)
        self.nameLineEdit.setToolTip("")
        self.nameLineEdit.setStatusTip("")
        self.nameLineEdit.setAccessibleDescription("")
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nameLineEdit)
        self.fullNameLabel = QtWidgets.QLabel(RelationForm)
        self.fullNameLabel.setObjectName("fullNameLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.fullNameLabel)
        self.fullNameLineEdit = QtWidgets.QLineEdit(RelationForm)
        self.fullNameLineEdit.setObjectName("fullNameLineEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.fullNameLineEdit)
        self.startDateLabel = QtWidgets.QLabel(RelationForm)
        self.startDateLabel.setObjectName("startDateLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.startDateLabel)
        self.startDateEdit = QtWidgets.QDateEdit(RelationForm)
        self.startDateEdit.setEnabled(True)
        self.startDateEdit.setWrapping(False)
        self.startDateEdit.setFrame(True)
        self.startDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.startDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.startDateEdit.setCalendarPopup(True)
        self.startDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.startDateEdit.setObjectName("startDateEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.startDateEdit)
        self.endDateLabel = QtWidgets.QLabel(RelationForm)
        self.endDateLabel.setObjectName("endDateLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.endDateLabel)
        self.endDateEdit = QtWidgets.QDateEdit(RelationForm)
        self.endDateEdit.setEnabled(True)
        self.endDateEdit.setWrapping(False)
        self.endDateEdit.setFrame(True)
        self.endDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.endDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.endDateEdit.setCalendarPopup(True)
        self.endDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.endDateEdit.setObjectName("endDateEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.endDateEdit)
        self.referenceLabel = QtWidgets.QLabel(RelationForm)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(RelationForm)
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.bankAccountLabel = QtWidgets.QLabel(RelationForm)
        self.bankAccountLabel.setObjectName("bankAccountLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.bankAccountLabel)
        self.bankAccountLineEdit = QtWidgets.QLineEdit(RelationForm)
        self.bankAccountLineEdit.setObjectName("bankAccountLineEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.bankAccountLineEdit)
        self.typeLabel = QtWidgets.QLabel(RelationForm)
        self.typeLabel.setObjectName("typeLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.typeLabel)
        self.typeComboBox = QtWidgets.QComboBox(RelationForm)
        self.typeComboBox.setObjectName("typeComboBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.typeComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 50, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonSave = QtWidgets.QPushButton(RelationForm)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.pushButtonReset = QtWidgets.QPushButton(RelationForm)
        self.pushButtonReset.setObjectName("pushButtonReset")
        self.horizontalLayout.addWidget(self.pushButtonReset)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RelationForm)
        QtCore.QMetaObject.connectSlotsByName(RelationForm)

    def retranslateUi(self, RelationForm):
        _translate = QtCore.QCoreApplication.translate
        RelationForm.setWindowTitle(_translate("RelationForm", "Form"))
        self.titleLabel.setText(_translate("RelationForm", "Relations"))
        self.pushButtonAdd.setText(_translate("RelationForm", "Add new"))
        self.pushButtonEdit.setText(_translate("RelationForm", "Edit"))
        self.pushButtonDelete.setText(_translate("RelationForm", "Delete"))
        self.nameLabel.setText(_translate("RelationForm", "Name"))
        self.fullNameLabel.setText(_translate("RelationForm", "Full Name"))
        self.startDateLabel.setText(_translate("RelationForm", "Start date"))
        self.endDateLabel.setText(_translate("RelationForm", "End date"))
        self.referenceLabel.setText(_translate("RelationForm", "Reference"))
        self.bankAccountLabel.setText(_translate("RelationForm", "Bank account"))
        self.typeLabel.setText(_translate("RelationForm", "Relation type"))
        self.pushButtonSave.setText(_translate("RelationForm", "Save"))
        self.pushButtonReset.setText(_translate("RelationForm", "Reset"))

