# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\transaction_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TransactionFormInsert(object):
    def setupUi(self, TransactionFormInsert):
        TransactionFormInsert.setObjectName("TransactionFormInsert")
        TransactionFormInsert.resize(286, 273)
        self.formLayout = QtWidgets.QFormLayout(TransactionFormInsert)
        self.formLayout.setObjectName("formLayout")
        self.contractLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.contractLabel.setObjectName("contractLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.contractLabel)
        self.letterComboBox = MyComboBox(TransactionFormInsert)
        self.letterComboBox.setObjectName("letterComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.letterComboBox)
        self.letterLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.letterLabel.setObjectName("letterLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.letterLabel)
        self.contractComboBox = MyComboBox(TransactionFormInsert)
        self.contractComboBox.setObjectName("contractComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.contractComboBox)
        self.referenceLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.referenceLabel.setObjectName("referenceLabel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.referenceLabel)
        self.referenceLineEdit = QtWidgets.QLineEdit(TransactionFormInsert)
        self.referenceLineEdit.setToolTip("")
        self.referenceLineEdit.setStatusTip("")
        self.referenceLineEdit.setAccessibleDescription("")
        self.referenceLineEdit.setObjectName("referenceLineEdit")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.referenceLineEdit)
        self.accountComboBox = MyComboBox(TransactionFormInsert)
        self.accountComboBox.setObjectName("accountComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accountComboBox)
        self.accountLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.accountLabel.setObjectName("accountLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.accountLabel)
        self.amountLineEdit = QtWidgets.QLineEdit(TransactionFormInsert)
        self.amountLineEdit.setObjectName("amountLineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.amountLineEdit)
        self.amountLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.amountLabel)
        self.transactionDateLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.transactionDateLabel.setObjectName("transactionDateLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.transactionDateLabel)
        self.dateDateEdit_2 = QtWidgets.QDateEdit(TransactionFormInsert)
        self.dateDateEdit_2.setEnabled(True)
        self.dateDateEdit_2.setWrapping(False)
        self.dateDateEdit_2.setFrame(True)
        self.dateDateEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dateDateEdit_2.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.dateDateEdit_2.setCalendarPopup(True)
        self.dateDateEdit_2.setDate(QtCore.QDate(2016, 7, 6))
        self.dateDateEdit_2.setObjectName("dateDateEdit_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dateDateEdit_2)
        self.dateLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.dateLabel.setObjectName("dateLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.dateLabel)
        self.dateDateEdit = QtWidgets.QDateEdit(TransactionFormInsert)
        self.dateDateEdit.setEnabled(True)
        self.dateDateEdit.setWrapping(False)
        self.dateDateEdit.setFrame(True)
        self.dateDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.dateDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.dateDateEdit.setCalendarPopup(True)
        self.dateDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.dateDateEdit.setObjectName("dateDateEdit")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.dateDateEdit)
        self.paymentStateLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.paymentStateLabel.setObjectName("paymentStateLabel")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.paymentStateLabel)
        self.paymentStateCheckBox = QtWidgets.QCheckBox(TransactionFormInsert)
        self.paymentStateCheckBox.setObjectName("paymentStateCheckBox")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.paymentStateCheckBox)
        self.debitLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.debitLabel.setObjectName("debitLabel")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.debitLabel)
        self.debitCheckBox = QtWidgets.QCheckBox(TransactionFormInsert)
        self.debitCheckBox.setObjectName("debitCheckBox")
        self.formLayout.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.debitCheckBox)

        self.retranslateUi(TransactionFormInsert)
        QtCore.QMetaObject.connectSlotsByName(TransactionFormInsert)

    def retranslateUi(self, TransactionFormInsert):
        _translate = QtCore.QCoreApplication.translate
        TransactionFormInsert.setWindowTitle(_translate("TransactionFormInsert", "Form"))
        self.contractLabel.setText(_translate("TransactionFormInsert", "Contract"))
        self.letterLabel.setText(_translate("TransactionFormInsert", "Letter"))
        self.referenceLabel.setText(_translate("TransactionFormInsert", "Reference"))
        self.accountLabel.setText(_translate("TransactionFormInsert", "Bank account"))
        self.amountLabel.setText(_translate("TransactionFormInsert", "Amount"))
        self.transactionDateLabel.setText(_translate("TransactionFormInsert", "Transaction date"))
        self.dateLabel.setText(_translate("TransactionFormInsert", "Payment date"))
        self.paymentStateLabel.setText(_translate("TransactionFormInsert", "Status"))
        self.paymentStateCheckBox.setText(_translate("TransactionFormInsert", "Payed?"))
        self.debitLabel.setText(_translate("TransactionFormInsert", "Debit/Credit"))

from MyQtness.myWidgets import MyComboBox
