# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PDE\projects\qt\pat\MyQtness\ui\transaction_form.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TransactionFormInsert(object):
    def setupUi(self, TransactionFormInsert):
        TransactionFormInsert.setObjectName("TransactionFormInsert")
        TransactionFormInsert.resize(286, 296)
        self.formLayout = QtWidgets.QFormLayout(TransactionFormInsert)
        self.formLayout.setObjectName("formLayout")
        self.contractLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.contractLabel.setObjectName("contractLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.contractLabel)
        self.contractComboBox = MyComboBox(TransactionFormInsert)
        self.contractComboBox.setObjectName("contractComboBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.contractComboBox)
        self.letterLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.letterLabel.setObjectName("letterLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.letterLabel)
        self.letterComboBox = MyComboBox(TransactionFormInsert)
        self.letterComboBox.setObjectName("letterComboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.letterComboBox)
        self.accountLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.accountLabel.setObjectName("accountLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.accountLabel)
        self.accountComboBox = MyComboBox(TransactionFormInsert)
        self.accountComboBox.setObjectName("accountComboBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.accountComboBox)
        self.amountLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.amountLabel.setObjectName("amountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.amountLabel)
        self.debitLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.debitLabel.setObjectName("debitLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.debitLabel)
        self.debitCheckBox = QtWidgets.QCheckBox(TransactionFormInsert)
        self.debitCheckBox.setObjectName("debitCheckBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.debitCheckBox)
        self.transactionDateLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.transactionDateLabel.setObjectName("transactionDateLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.transactionDateLabel)
        self.transactionDateEdit = QtWidgets.QDateEdit(TransactionFormInsert)
        self.transactionDateEdit.setEnabled(True)
        self.transactionDateEdit.setWrapping(False)
        self.transactionDateEdit.setFrame(True)
        self.transactionDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.transactionDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.transactionDateEdit.setCalendarPopup(True)
        self.transactionDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.transactionDateEdit.setObjectName("transactionDateEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.transactionDateEdit)
        self.paymentStateLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.paymentStateLabel.setObjectName("paymentStateLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.paymentStateLabel)
        self.paymentStateCheckBox = QtWidgets.QCheckBox(TransactionFormInsert)
        self.paymentStateCheckBox.setObjectName("paymentStateCheckBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.paymentStateCheckBox)
        self.paymentDateLabel = QtWidgets.QLabel(TransactionFormInsert)
        self.paymentDateLabel.setObjectName("paymentDateLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.paymentDateLabel)
        self.paymentDateEdit = QtWidgets.QDateEdit(TransactionFormInsert)
        self.paymentDateEdit.setEnabled(True)
        self.paymentDateEdit.setWrapping(False)
        self.paymentDateEdit.setFrame(True)
        self.paymentDateEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.paymentDateEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2016, 7, 6), QtCore.QTime(0, 0, 0)))
        self.paymentDateEdit.setCalendarPopup(True)
        self.paymentDateEdit.setDate(QtCore.QDate(2016, 7, 6))
        self.paymentDateEdit.setObjectName("paymentDateEdit")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.paymentDateEdit)
        self.amountCurrencyEdit = MyCurrencyBox(TransactionFormInsert)
        self.amountCurrencyEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.amountCurrencyEdit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.amountCurrencyEdit.setObjectName("amountCurrencyEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.amountCurrencyEdit)

        self.retranslateUi(TransactionFormInsert)
        QtCore.QMetaObject.connectSlotsByName(TransactionFormInsert)

    def retranslateUi(self, TransactionFormInsert):
        _translate = QtCore.QCoreApplication.translate
        TransactionFormInsert.setWindowTitle(_translate("TransactionFormInsert", "Form"))
        self.contractLabel.setText(_translate("TransactionFormInsert", "Contract"))
        self.letterLabel.setText(_translate("TransactionFormInsert", "Letter"))
        self.accountLabel.setText(_translate("TransactionFormInsert", "Bank account"))
        self.amountLabel.setText(_translate("TransactionFormInsert", "Amount"))
        self.debitLabel.setText(_translate("TransactionFormInsert", "Debit/Credit"))
        self.transactionDateLabel.setText(_translate("TransactionFormInsert", "Transaction date"))
        self.paymentStateLabel.setText(_translate("TransactionFormInsert", "Status"))
        self.paymentStateCheckBox.setText(_translate("TransactionFormInsert", "Payed?"))
        self.paymentDateLabel.setText(_translate("TransactionFormInsert", "Payment date"))

from MyQtness.myWidgets import MyComboBox, MyCurrencyBox
