"""First migration ever!!

Revision ID: a5842a716720
Revises: 
Create Date: 2016-09-02 07:33:08.236731

"""

# revision identifiers, used by Alembic.
revision = 'a5842a716720'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import db.qvariantalchemy


def upgrade():
    with op.batch_alter_table('contracts'):
        ### commands auto generated by Alembic - please adjust! ###
        op.add_column('contracts', sa.Column('contract_type_id', db.qvariantalchemy.Integer(), nullable=True))
        op.create_foreign_key(None, 'contracts', 'types', ['contract_type_id'], ['id'])
        op.drop_column('contracts', 'contract_type')
        op.drop_column('contracts', 'amount')
    with op.batch_alter_table('types'):
        op.add_column('types', sa.Column('contract', db.qvariantalchemy.String(), nullable=True))
        ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('types', 'contract')
    op.add_column('contracts', sa.Column('amount', sa.INTEGER(), nullable=True))
    op.add_column('contracts', sa.Column('contract_type', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'contract_type_id')
    ### end Alembic commands ###
